#!/bin/bash

# Exit on any error
set -e

echo "Starting Home Assistant setup script..."

# Step 0: Enable USB Boot on Raspberry Pi
echo "--- Enabling USB Boot ---"
sudo apt update
sudo apt full-upgrade -y
sudo rpi-eeprom-update -a
#echo "USB Boot enabled. Please reboot your Raspberry Pi and ensure you are booting from the SSD."
#echo "Press Enter to continue after rebooting..."
#read

# Step 1: Install Docker
echo "--- Installing Docker ---"
sudo apt install -y docker.io docker-compose
sudo systemctl enable docker
echo "Docker installed and enabled."

# Step 2: Install Tailscale
echo "--- Installing Tailscale ---"
sudo apt install -y curl lsb-release
curl -fsSL https://pkgs.tailscale.com/stable/raspbian/$(lsb_release -cs).noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
echo "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/raspbian $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/tailscale.list
sudo apt-get update
sudo apt-get install -y tailscale
echo "Tailscale installed."

# Step 3: Set Hostname
echo "--- Setting Hostname ---"
sudo hostnamectl set-hostname homeassistant
echo "Hostname set to 'homeassistant'. Please reboot for the changes to take effect."

# Step 3: Create directories and set permissions
echo "--- Creating directories and setting permissions ---"
mkdir -p ha-config appdaemon influxdata grafana
sudo chown -R 1000:1000 ha-config
sudo chown -R 5050:5050 appdaemon
sudo chown -R 1000:1000 influxdata
sudo chown -R 472:472 grafana
echo "Directories created and permissions set."

# Step 4: Prepare Secrets File
echo "--- Preparing Secrets File ---"
if [ -f "ha-config/secrets.yaml" ]; then
    echo "secrets.yaml already exists. Skipping creation."
else
    echo "Creating secrets.yaml with generated passwords..."
    GRAFANA_PASSWORD=$(head -c 32 /dev/urandom | base64)
    INFLUXDB_PASSWORD=$(head -c 32 /dev/urandom | base64)

    cat << EOF > ha-config/secrets.yaml
# This file was automatically generated by setup.sh

# Home Assistant
ha_token: your-long-lived-ha-token

# InfluxDB
influxdb_admin_token: your-influx-admin-token
influxdb_password: ${INFLUXDB_PASSWORD}

# Grafana
grafana_password: ${GRAFANA_PASSWORD}

EOF
    echo "secrets.yaml created with new random passwords for Grafana and InfluxDB."
fi


# Install yq
sudo apt install -y yq
# Input YAML file
YAML_FILE="ha-config/secrets.yaml"
# Output .env file
ENV_FILE=".env"
# Convert YAML to .env with uppercase keys
yq -r 'to_entries | .[] | (.key | ascii_upcase) + "=" + (.value | tostring)' "$YAML_FILE" > "$ENV_FILE"


echo "Converted YAML to .env file with uppercase keys at $ENV_FILE"

echo "--- Setup Complete ---"
echo "Next steps:"
echo "1. Reboot your Raspberry Pi if you haven't already."
echo "2. Run 'sudo tailscale up' to connect to your Tailscale network."
echo "3. IMPORTANT: You still need to generate tokens for Home Assistant and InfluxDB."
echo "   Follow the instructions in the README.md to generate these tokens and add them to ha-config/secrets.yaml."
echo "4. Run './start.sh' to start all the services."
